### ISSUE TITLE
Section 4 - App Sketch & Brief Description

### ISSUE THREAD

**Issue by jbarns14** [UBC-MDS/DSCI-532_2024_15_dreamhouse#4]
Create a sketch of what you envision your app to look like. Your sketch can be hand-drawn or put together using a graphics editor or slide show software. The sketch should be saved as img/sketch.png and linked in this section of the proposal so that the image shows up when reading the proposal on GitHub.

Complement the sketch with a high level description of the main components in the app interface and how the user will interact with it. You are not required to use terminology specific to Dash/Shiny (i.e. widgets, components, etc...).

**Comment by zgarciaj** [comment]
Hey team,

Hope you're all doing well! I'm diving into our dashboard sketch and wanted to touch base on a few details before drafting the writeup for this section:

Are we thinking of placing the price range filter with the rest of the filters, or did we settle on having it under the map chart as we chatted about earlier today?
<img width="1509" alt="op_1" src="https://github.com/UBC-MDS/DSCI-532_2024_15_dreamhouse/assets/65718524/8622fe8e-ad1b-456b-bc94-ae9f8a86ec85">
Or
<img width="981" alt="op_2" src="https://github.com/UBC-MDS/DSCI-532_2024_15_dreamhouse/assets/65718524/68639c2a-32cd-4165-8e5f-86c0935d4dc9">

(Just for fun I also did Selecting State: Texas)
<img width="981" alt="by_state" src="https://github.com/UBC-MDS/DSCI-532_2024_15_dreamhouse/assets/65718524/ebc5f630-8411-47ff-b0cf-45031a036882">

I’d also love your thoughts on a few other things:
- What other info should we pack into the tooltips?
- Any tweaks needed for our number summaries?
- Should we reconsider any of the widget types for the filters?

If you have any suggestions or anything you’d like tweaked, just let me know!

**Comment by lichunubc** [comment]
Wow, that has raised the bar so high. Amazing work Zeily

**Comment by jbarns14** [comment]
That looks amazing! Great work! What a start to the project!

**Comment by sungg888** [comment]
Amazing work Zeily! That looks so cool!
