### ISSUE TITLE
Feedback from Joel

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_15_dreamhouse#43]
Major:
- [x] Cities show up on map when the map is zoomed in
    - [ ] Hover either map or bar and highlight in both
- [x] Default view should be states and message to select to show cities
    - [ ] Bars a bit too 
    - [ ] More bars than labels
- [x] Fix color bar range to the range of all states

Minor:
- [x] Overlap in median household labels
- [x] Legend meaningless after choosing a state
- [ ] Remove the city level
- [x] Median for all cards 
- [x] Format numbers on cars: thousands 
- [ ] Frame dashboards with title/navbar with background? Maybe frame with sidebar color too?

**Comment by sungg888** [comment]
done
