### ISSUE TITLE
Peer feedback - Julia

### ISSUE THREAD

**Issue by juliaeveritt** [UBC-MDS/DSCI-532_2024_15_dreamhouse#44]
Hi! Great work on this :) A few points of feedback:

* It would be really helpful to add a description at the top of the dashboard under the title. I found it a bit confusing to figure out which plots were interactive and what the intended workflow is at first
* I like the layout of the app and how nicely it fits onto the screen with well-placed whitespace
* App functionality is well suited to the target audience, very informative
* The axis labels on median household income are too close together to read for me, would be good to adjust the ticks

**Comment by sungg888** [comment]
done
