### ISSUE TITLE
Feedback from Mohammad

### ISSUE THREAD

**Issue by MoNorouzi23** [UBC-MDS/DSCI-532_2024_15_dreamhouse#45]
Hello everyone,

Great job on the dashboard! I've reviewed it and I'm impressed with the comprehensive data and interactive elements you've included. Here are some suggestions for improvement:

-Consider linking the bar plot to the state filter instead of using separate filters for state and city. This would prevent situations where some states have only one city resulting in a single bar, which may not be useful for all users.

-Simplify the dashboard by reducing the number of filters. For example, having just one filter for price could make navigation easier. Also, ensure that the dashboard updates properly with all filters and avoid displaying NaN values.

-Allow multiple selections in the main filters to enhance user understanding of the market.

-Set limitations for certain filters, such as beds (e.g., from 1 to 10), to provide a more focused user experience.

-Maintain consistency in visual presentation, such as using the same format for displaying prices (e.g., median price and median household income) and considering adding a "$" symbol to the tooltip in the map. Additionally, consider using integers for average bed or bath counts for clarity.

Thanks again for your hard work!

**Comment by sungg888** [comment]
done
