### ISSUE TITLE
Peer Feedback- Rafe

### ISSUE THREAD

**Issue by rafecchang** [UBC-MDS/DSCI-532_2024_15_dreamhouse#46]
Hello team, there were some errors I ran into while trying to pull up the dashboard: 

- In README, this line `conda activate environment` should be replaced with `conda activate Dreamhouse` 
- Also when I try to run python app.py after cloning the file it was showing that `FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/processed_df.csv'`
- The link- https://github.com/UBC-MDS/DSCI-532_2024_15_dreamhouse/blob/main/dsci-532-2024-15-dreamhouse-odas.onrender.com does not work. 

I think these issues all occur because you guys are currently working on it

**Comment by sungg888** [comment]
done
