### ISSUE TITLE
Feedback from Allan Lee (Yu Lun)

### ISSUE THREAD

**Issue by allan8392** [UBC-MDS/DSCI-532_2024_15_dreamhouse#60]
- The app response time is a little slow.
  Our group had similar problem.
  We improved the speed by building index for the the dataframe.
  In your case I believe you can set state and city as index and it will speed up the app a little.
- The color scale for the map is hard to read.
  When the color is near the top or bottom, they look pretty similar.
  (I am color deficient by the way. Maybe others do not have the the same issue)
- Color and legend for the bar chart is not needed. You are already labelling city on the x axis.
- Decimal can be eliminated for all card numbers.
- Selection boxes for beds and baths need to be labelled. I believe you are filtering for min max?
  I have to guess since you do not have label. 
- title for bard chart and map are not aligned.
- I think the app provides useful information for your intended users

**Comment by sungg888** [comment]
done
