### ISSUE TITLE
Feedback from Joel M4

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_15_dreamhouse#64]
Implement two major and four minor

Major:

- Use color from map to color bars and:
    - Remove bar legend
    - Remove or rotate map legend
    - Figure out map coolor scale
    - Make map bigger
    - Switch map to bar to median
- Remove fips, and city from maps tooltip. Show cities as dots with label to make it clear. Merge counties.
- Fix map performance (or loading spinners but then it's a minor item)

Minor:

- Hover either map or bar and highlight in both
- Get rid of decimals from cards
- Remove y-axis label city
- Explore some framing, e.g. side bar or title bar in color. 
- Center text in card
- Make sure boxes min/max don't overlap
- Map should filter even

**Comment by sungg888** [comment]
done
