### ISSUE TITLE
Main Map Improvement to-do list for M4

### ISSUE THREAD

**Issue by lichunubc** [UBC-MDS/DSCI-532_2024_15_dreamhouse#69]
For the main map:
Remove or rotate map legend (Will try rotating it if possible, otherwise it will be removed)
Figure out map color scale
Make map bigger
Remove fips, and city from maps tooltip. Show cities as dots with label to make it clear. Merge counties
Fix map performance (or loading spinners but then it's a minor item)

**Comment by lichunubc** [comment]
- Color scale legend is now horizontal and is underneath the map, and will dynamically adjust the range based on state selections.
- Hovering will no longer display city info. I have tried to remove the fips_str but I could not do it. Instead, I have renamed fips_str to FIPS which looks nicer

**Comment by sungg888** [comment]
done
